name: prueba-POC

on: [push]
       
jobs:  
  clair-scan:
    name: Scan image with Clair
    runs-on: ubuntu-latest
    steps:
    - name: Pull image to local registry
      run: docker pull vulnerables/web-dvwa:latest
    - name: Clair Test
      id: clairtest
      uses: the-iron-bank-of-braavos/clair@fix/local-and-remote
      with:
       image: "vulnerables/web-dvwa:latest"
       report_format: xml
       updater: debian
       report_path: clair-report.xml
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: clair-result
        path: clair-report.xml
